# 1.Conver in to lower case;

In [3]:
import pandas as pd;
import numpy as np;

In [4]:
data=pd.read_csv("Data/IMDB_Dataset.csv")

In [5]:
data.shape


(50000, 2)

In [6]:
data.head()


review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data['review'][3]

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [6]:
data['review'][3].lower()

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [7]:
data['review']=data['review'].str.lower()
#conver and store in your data

In [8]:
data.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# 2.Remove unwanted symbol or thing from data

# 2.1 Remove HTML tag

In [9]:
import re
#  re stand for regular expression
def remove_html_tag(text):
    pattern=re.compile('<.*?>') #<.*?> html tag indicator 
    return pattern.sub(r'',text)

In [10]:
text="<br /><br />This movie is slower "
remove_html_tag(text)

'This movie is slower '

In [11]:
#now apply it to hole dataset;
data['review'].apply(remove_html_tag)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. the filming tec...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot, bad dialogue, bad acting, idiotic di...
49997    i am a catholic taught in parochial elementary...
49998    i'm going to have to disagree with the previou...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [12]:
data['review']=data['review'].apply(remove_html_tag)

In [13]:
data.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

# 2.2 Remove punchuation 

1.manual methode or normal method of removing punctuation which take long time

In [14]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [15]:
exclude=string.punctuation

In [16]:
def remove_punc(text):
    for char in exclude:
        text=text.replace(char,'')
    return text

In [17]:
text='hey ../ how @are you*#'

In [18]:
start=time.time()
print(remove_punc(text))
time1=time.time()-start
print("time taken to remove punctuation:",time1*50000)

hey  how are you
time taken to remove punctuation: 60.35566329956055


In [19]:
text1='hey ../ how @are you*#'

2.Faster method

In [20]:
def remove_punc1(text):
    return text.translate(str.maketrans('','',exclude))

In [21]:
start=time.time()
print(remove_punc1(text1))
time2=time.time()-start
print("time taken to remove punctuation:",time2*50000)

hey  how are you
time taken to remove punctuation: 50.008296966552734


In [22]:
print("second method is ",time1/time2, " time faster then first method")

second method is  1.2069129916567343  time faster then first method


In [23]:
#removing from our actual data
data.sample()

review sentiment
31955  this was the most visually stunning, moving, a...  positive

In [24]:
data['review'].apply(remove_punc1)

0        one of the other reviewers has mentioned that ...
1        a wonderful little production the filming tech...
2        i thought this was a wonderful way to spend ti...
3        basically theres a family where a little boy j...
4        petter matteis love in the time of money is a ...
                               ...                        
49995    i thought this movie did a down right good job...
49996    bad plot bad dialogue bad acting idiotic direc...
49997    i am a catholic taught in parochial elementary...
49998    im going to have to disagree with the previous...
49999    no one expects the star trek movies to be high...
Name: review, Length: 50000, dtype: object

In [25]:
data['review']=data['review'].apply(remove_punc1)
data.head()

review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

# 3.Spelling correction

In [1]:
from textblob import TextBlob
incorrect_text=" my friand is goode persion"
textBlb=TextBlob(incorrect_text)
textBlb.correct().string

' my friend is good person'

# 4.Remove Stop word
stop work are those work which contribute in sentence formation like i,my,is,are,they etc..

In [27]:
from nltk.corpus import stopwords
#Natural Language Toolkit(nltk)
#corpus package contain the list of stopword in many languages


# Natural Language Toolkit(nltk)
NLTK is a standard python library that provides a set of diverse algorithms for NLP. It is one of the most used libraries
for NLP and Computational Linguistics

In [28]:
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [29]:
import nltk
nltk.download('stopwords')


[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Ritesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [30]:
def remove_stopword(text):
    new_txt=[]
    
    for word in text.split(): #for break our word text by text
        if(word in stopwords.words('english')):
            new_txt.append('')
        else:
            new_txt.append(word)
    x=new_txt[:] #copy new data which do not contain stopword;
    new_txt.clear()# removing so that it can be used again ..
    #if we not clear then data will be appended to old one
        
    return " ".join(x)

In [31]:
text="i am going to markets"
remove_stopword(text)

'  going  markets'

In [ ]:
#appling in whole dataset;
data['review']=data['review'].apply(remove_stopword)
data.head()

In [ ]:
import emoji
print(emoji.demojize('this movies is 😴'))

# 5.Tokenization



5.1 using simple `split()` function

In [ ]:
#word tokennization
sent1="I am going to delhi"
sent1.split()

In [ ]:
sent2="I am going to delhi!"
sent2.split()

In [ ]:
#sentence tokenization
sent3="I am going to delhi. You are comming with us?"
sent3.split('.')

...............................................................................................................................

5.2 `Regular expression`

In [ ]:
import re
sent4='I am going to Delhi! and You will. come with #us?'
result=re.findall("\w+",sent4)#for all punchuation
result

In [ ]:
text5="Natural language processing (NLP) is a machine learning technology that gives computers the ability to interpret, manipulate, and comprehend human language."
result2=re.compile('[.,?]').split(text5)
result2

................................................................................................................

5.3 `NLTK`

In [1]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [2]:
example1="I am @going to# Delhi."
word_tokenize(example1)

['I', 'am', '@', 'going', 'to', '#', 'Delhi', '.']

In [ ]:
import nltk
nltk.download('punkt')

In [ ]:
example2="I have done Ph.D in A.I."
word_tokenize(example2)

In [4]:
ex1='I have done #Ph.D in A.I.'
ex2="We're here  mail on ritesh12@gmail.com"
ex3='A 5km ride cost is $10.50'

In [5]:
word_tokenize(ex1) #here works fine

['I', 'have', 'done', '#', 'Ph.D', 'in', 'A.I', '.']

In [ ]:
word_tokenize(ex2) #fail in some case like gmail

In [ ]:
word_tokenize(ex3) #fail in 5km

........................................................................

5.4 `Spacy` work more accurretly

# 6.Stemming

Stemming is the process of removing the last few characters
of a given word, to obtain a shorter form, even if that form doesn’t have any meaning.



In [1]:
from nltk.stem.porter import PorterStemmer

In [2]:
ps=PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [3]:
sample="walking  walked walks"
stem_words(sample)

'walk walk walk'

In [4]:
sample2="Stemming is the process of reducing a word to its stem that affixes to suffixes and prefixes or to the roots of words known as lemmas."

In [5]:
stem_words(sample2) #fast
#it do stemming but its not nessesary that it give right word. it do in it own style

'stem is the process of reduc a word to it stem that affix to suffix and prefix or to the root of word known as lemmas.'

# 6.Lemmatization

Lemmatization reduces the inflected words properly, ensuring the root word belongs to the language. 
In Lemmatization, the root word is called Lemma.
A Lemma is a canonical form, dictionary form, or citation form of a set of words.

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer
lemma=WordNetLemmatizer()

text='hii how are you? hope you are doing well.He played game '
punctuation="?:!.,"
sentance_word=nltk.word_tokenize(text)
for word in sentance_word:
    if word in punctuation:
        sentance_word.remove(word)
sentance_word


In [ ]:
print("{0:20}{1:20}".format("Word","Lemma"))

In [ ]:
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentance_word:
    print("{0:20}{1:20}".format(word,lemma.lemmatize(word,pos='v')))

In [ ]:
>>> import nltk
>>> nltk.download('wordnet')

In [2]:
import numpy as np 
import pandas as pd

data1={"review":["not good movies","ok not baad","i like this movies"]}
df=pd.DataFrame(data1)
df

review
0     not good movies
1         ok not baad
2  i like this movies

# One Hot Encoding

In [4]:
data1['review'][1]

'ok not baad'

# One Hot Encoding using `Bag of Word`
**bag of word is a special case of `n-gram`
**where ngram_range=(1,1) or we can say unigram
**unigram means taking every word

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer()
bow=count_vect.fit_transform(df['review'])


In [12]:
#vocabulary
print(count_vect.vocabulary_)

{'not': 4, 'good': 1, 'movies': 3, 'ok': 5, 'baad': 0, 'like': 2, 'this': 6}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0 1 1 0 0]]
[[1 0 0 0 1 1 0]]
[[0 0 1 1 0 0 1]]


disadvantage

1.`sparcity`
2.`out of vocabulary`
3.`ordering`

# One Hot Encoding using `n-gram`

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer(ngram_range=(2,2))
bow=count_vect.fit_transform(df['review'])
print(count_vect.vocabulary_)

{'not good': 3, 'good movies': 0, 'ok not': 4, 'not baad': 2, 'like this': 1, 'this movies': 5}


In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[1 0 0 1 0 0]]
[[0 0 1 0 1 0]]
[[0 1 0 0 0 1]]


In [16]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer(ngram_range=(1,2))  #(1,2) means combination of 1 and twos words
bow=count_vect.fit_transform(df['review'])
print(count_vect.vocabulary_)

{'not': 6, 'good': 1, 'movies': 5, 'not good': 8, 'good movies': 2, 'ok': 9, 'baad': 0, 'ok not': 10, 'not baad': 7, 'like': 3, 'this': 11, 'like this': 4, 'this movies': 12}


In [17]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect=CountVectorizer(ngram_range=(3,3))  #(3,3) means combination of 3 words
bow=count_vect.fit_transform(df['review'])
print(count_vect.vocabulary_)

{'not good movies': 1, 'ok not baad': 2, 'like this movies': 0}


In [18]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 0]]
[[0 0 1]]
[[1 0 0]]


Disadvantage 
  **out of vocabulary
  **Make algo slow
  
advantage
   **simple
   **able to captuare sementic of the sentance

# TF-IDF

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
TF_IDF=TfidfVectorizer()
TF_IDF.fit_transform(df['review']).toarray()

array([[0.        , 0.68091856, 0.        , 0.51785612, 0.51785612,
        0.        , 0.        ],
       [0.62276601, 0.        , 0.        , 0.        , 0.4736296 ,
        0.62276601, 0.        ],
       [0.        , 0.        , 0.62276601, 0.4736296 , 0.        ,
        0.        , 0.62276601]])

In [9]:
print(TF_IDF.idf_)
print(TF_IDF.get_feature_names_out())

[1.69314718 1.69314718 1.69314718 1.28768207 1.28768207 1.69314718
 1.69314718]
['baad' 'good' 'like' 'movies' 'not' 'ok' 'this']
